---
- name: Remove podman
  become: yes
  dnf:
    name: podman-docker
    state: absent

- name: Add Docker repo
  become: yes
  command:
    cmd: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"

- name: Install Docker
  become: yes
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Start and enable Docker service
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
