---
- name: Remove podman
  become: yes
  dnf:
    name: podman-docker
    state: absent

- name: Add Docker repo
  become: yes
  command:
    cmd: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"

- name: Install Docker
  become: yes
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Start and enable Docker service
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create docker group
  become: yes
  group:
    name: docker
    state: present

- name: "add user {{ansible_user}} to docker group"
  become: yes
  user:
    name: "{{user}}"
    groups: docker
    append: yes
