---
- name: Install RPM Fusion Free
  become: yes
  dnf:
    disable_gpg_check: yes
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install RPM Fusion Non Free
  become: yes
  dnf:
    disable_gpg_check: yes
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install common packages
  become: yes
  dnf:
    name:
      - vim
      - htop
      - vlc
      - VirtualBox
      - vagrant
      - gnome-tweaks
      - lm_sensors
      - dnf-plugins-core # Used by to install Docker

# - name: Install VSCode
#   block:
#     - name: Download VSCode RPM
#       get_url:
#         url: https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64
#         dest: ~/Downloads/vscode.rpm
#         mode: "u+rwx"
#         force: yes

#     - name: Install VSCode
#       become: yes
#       dnf:
#         name: ~/Downloads/vscode.rpm

# - name: Install Google Chrome
#   block:
#     - name: Download Google Chrome RPM
#       get_url:
#         url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
#         dest: ~/Downloads/google-chrome.rpm
#         mode: "u+rwx"
#         force: yes

#     - name: Install Google Chrome
#       become: yes
#       dnf:
#         name: ~/Downloads/google-chrome.rpm

- name: Set vim as default editor
  lineinfile:
    path: ~/.bash_profile
    line: "export EDITOR=vim"
