---
- name: Install RPM Fusion Free
  become: yes
  dnf:
    disable_gpg_check: yes
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install RPM Fusion Non Free
  become: yes
  dnf:
    disable_gpg_check: yes
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install common packages
  become: yes
  dnf:
    name:
      - vim
      - htop
      - vlc
      - VirtualBox
      - vagrant
      - gnome-tweaks
      - lm_sensors
      - dnf-plugins-core # Used by to install Docker

- name: Install AppImageLauncher
  become: yes
  dnf:
    name: "https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm"

- name: Set vim as default editor
  lineinfile:
    path: ~/.bash_profile
    line: "export EDITOR=vim"
